Correções fileHandler_test
1 - src/utility/fileHandler/fileHandler_test.go:104:24: Error return value of `fileHandler.DeleteFile` is not checked (errcheck)
2 - src/utility/fileHandler/fileHandler_test.go:5:2: SA1019: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)}
3 - src/utility/fileHandler/fileHandler_test.go:207:25: SA4010: this result of append is never used, except maybe in other appends (staticcheck)
#0 2.983                        createdDirectories = append(createdDirectories, path)